---
title: "Running cybrBSA Easily"
author: "Cassandra Buzby"
date: "`r Sys.Date()`"
output: html_document
---

# Functions for running everything in a way that is easier

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

#Load packages
library(tidyverse)
library(dplyr)
library(cybrBSA)

```

# Collection of all functions

```{r}
ez_getrawdata <- function(tablefilename){
  ChromKey <- data.frame(chromosomes = c("I", "II", "III", "IV", "V", "VI", "VII", "VIII", 
                                       "IX", "X", "XI", "XII", "XIII", "XIV", "XV", "XVI", "M"), 
                       CHROM = c("NC_001133.9", "NC_001134.8", "NC_001135.5", "NC_001136.10", 
                                 "NC_001137.3", "NC_001138.5", "NC_001139.9", "NC_001140.6", 
                                 "NC_001141.2", "NC_001142.9", "NC_001143.9", "NC_001144.5", 
                                 "NC_001145.3", "NC_001146.8", "NC_001147.6", "NC_001148.4", "NC_001224.1"))
  
  cybrInputGATKTable(tablefilename) %>% mutate(Coverage = as.numeric(AD.REF) + as.numeric(AD.ALT)) %>%
  select(POS, CHROM, Dataset, GQ, AD.REF, AD.ALT, Coverage) -> rawdata
  
  return(rawdata)
}

ez_callSNPs <- function(mydata = rawdata, parentSNPs){
  
  if(missing(parentSNPs)){
    parentSNPs <- cybrConvertParentalAlleles(Truncate = TRUE)
  }

  mydata %>% 
    merge(parentSNPs) %>% 
    mutate(REFW = as.numeric(Type == "Wine"), REFO = as.numeric(Type == "Oak")) %>%
    group_by(Dataset, CHROM, POS) %>%
    mutate(Wine = max(REFW * as.numeric(AD.REF), REFO * as.numeric(AD.ALT)),
           Oak = max(REFW * as.numeric(AD.ALT), REFO * as.numeric(AD.REF))) %>%
    select(Dataset, POS, CHROM, Coverage, Wine, Oak) %>%
    pivot_longer(c(Oak, Wine), names_to = "Allele", values_to = "Reads") -> called.output
  
  return(called.output)
}

ez_smooth <- function(mydata = rawdata_called, window = 200, myfunction = cybr_weightedgauss, myalignment = "center"){
  
  require(data.table)

  mydata %>% group_by(Dataset, CHROM, Allele) %>% arrange(POS) %>%
  reframe(POS = POS, 
          SmoothCount = ceiling(frollapply(Reads, n = window, FUN = myfunction, align = myalignment))
          ) -> smoothed.output
  
  return(smoothed.output)

}

ez_colselect <- function(mydata = rawdata_smoothed,
                       datasetcol = "Dataset",
                       separator = "[_.]",
                       mode = "SELECTCOLS",
                       library, droplist = "B", keeplist = "C"){
  
  n_cols <- max(lengths(strsplit(mydata[[datasetcol]], separator)))
  
  mydata %>%
    #head(10) %>%
    separate(datasetcol, into = LETTERS[1:n_cols], sep = separator) -> temp
  
  if(mode == "SELECTCOLS"){
    
    cat("You are using ez_glmprep in SELECTCOLS mode. To switch, please set mode to 'FILTERCOLS'","\n" )
    for(k in unique(temp$A)){
      temp.a <- temp %>% filter(A == k)
      
      cat(paste("\n","### In library", k,"###", "\n"))
      
      for(i in LETTERS[2:n_cols]){
      #cat(i,"\n")
      cat("Col", i, ":", unique(temp.a[[i]]),"\n")
      }
    }
  }else if(mode == "FILTERCOLS"){
      mycols <- LETTERS[1:n_cols]
      losers <- mycols[mycols %in% droplist | (mycols %in% keeplist)== FALSE]
      
    if(missing(library)){
      temp %>% select(colnames(temp)[colnames(temp) %in% losers == FALSE]) %>%
      na.omit() -> filtered.output
    
    return(filtered.output)
    }else{
       temp %>% filter(A == library) %>%
        select(colnames(temp)[colnames(temp) %in% losers == FALSE]) %>%
      na.omit() -> filtered.output
    
    return(filtered.output)
    }
  }
}

ez_glmprep.setcontrasts <- function(mydata, colname, ctrl, exp){
  mysubset <- mydata[mydata[[colname]] %in% c(ctrl, exp),]
  mysubset[[colname]] <- factor(mysubset[[colname]], levels = c(ctrl, exp))
  
  contrasts(mysubset[[colname]]) <- c(0,1)
  
  return(mysubset)
}

ez_glm.single <- function(mydatainput, 
                          dropchroms = c("M"),
                       AlleleCol = "Allele",
                       ExpCol = "E",
                       ReadsCol = "SmoothCount"){
  
  myformula = "Allele ~ E"
  
  mydatainput$Allele <- mydatainput[[AlleleCol]]
  mydatainput$E <- mydatainput[[ExpCol]]
  mydatainput$weights <- mydatainput[[ReadsCol]]
  
  mydatainput %>% na.omit() %>% 
  filter(CHROM %in% dropchroms == FALSE) %>%
  group_by(CHROM, POS) %>%
  mutate_if(is.character, as.factor) %>%
  summarize(summary = glm_cb2_short(Allele = Allele,
                             E = E,
                             W = weights, #use the weights variable from test
                             formula = myformula,
                             outputlength = 2),
            #MAKE SURE THIS IS THE SAME LENGTH AS OUTPUT LENGTH
            Factor = (c("Intercept", "E"))) -> processed_glm_all
  
  return(processed_glm_all)
}

ez_plotting <- function(glmoutput, absolutevalue = TRUE,
                        dropintercept = TRUE,
                        chroms = c("All"),
                        cutoff){
  
  require(ggplot2)
  
  if(dropintercept == TRUE){
    glmoutput %>% filter(Factor != "Intercept") -> glmoutput
  }
  
  if(chroms != "All"){
    glmoutput %>% filter(CHROM %in% chroms) -> glmoutput
  }
  
  if(absolutevalue == TRUE){
    glmoutput$summary <- abs(glmoutput$summary)
  }
  
  glmoutput %>% 
      ggplot(aes(x = POS, y = summary, color = Factor)) + geom_line() +
      ylab("z-score") +
      facet_grid(~CHROM, scales = "free", space = "free") +
      theme_bw() +
      theme(legend.position = "bottom") -> plotoutput
  
  if(missing(cutoff) == FALSE){
    plotoutput + geom_hline(aes(yintercept = cutoff), linetype = "dashed") -> plotoutput
  }
  
  return(plotoutput)
    
}

```

# Example usage of all functions

```{r}
#Input is vcf output table
rawdata <- ez_getrawdata(tablefilename = "HGV.SortedCat.vcf.output.table")

#add SNPs to the data frame
rawdata_called <- ez_callSNPs(mydata = rawdata)

####
#HERE: Donnell, if you want to sum all of your positions, I'd do that before smoothing (an example is here):
rawdata_called %>% group_by(Dataset, CHROM, POS, Allele) %>%
  summarize(Reads = sum(Reads, na.rm = TRUE)) -> rawdata_called2
####

#smooth the reads column; MUST be named "Reads"
rawdata_smoothed <- ez_smooth(rawdata_called)

#print out which columns are which
ez_colselect(mydata = rawdata_smoothed, 
             mode = "SELECTCOLS")

#use the above to select columns
dtest <- ez_colselect(mydata = rawdata_smoothed, mode = "FILTERCOLS", 
                      library = "HNGLVDRXY", keeplist = c("E"))

#set up what the control and experiment groups are for your bulk (experiment) column
#CHANGE THESE ARGUMENTS
torun <- ez_glmprep.setcontrasts(mydata = dtest, colname = "E", ctrl = "UnselectedA", exp = "UnselectedC")

#run a single variable logistic regression
outputglm <- ez_glm.single(torun)

#plot the output of the logistic regression
ez_plotting(outputglm, cutoff = 0.5)

```

