---
title: "AllExperiments_Plotting"
author: "Cassandra Buzby"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(ggplot2)
require(tidyr)
require(dplyr)
require(reshape2)
require(cowplot)
require(data.table)

require(doParallel)
require(RColorBrewer)
require(scales)
require(circlize) 
require(stringr)
require(ggrepel)

require(cybrBSA)
require(lme4)

ggplot2::theme_set(theme_minimal() + theme(text = element_text(size = 10)) +
                     theme(#axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()))
```

How to initially process the files

```{bash, eval = FALSE}
#Put everything in the same folder and run
Rscript SinglePoolProcess.R FilenameInFolder NameYouWant MQC_Annotated_REVISED.csv

#Or as a for loop
for i in $(ls *output.table); do Rscript SinglePoolProcess.R $i $i MQC_Annotated_REVISED.csv; done
```

## Load in processed GLMs

```{r}
Fluc_G200 <- readRDS("Fluc2025G200.rds")
H2O2_G200 <- readRDS("H2O2.SortedCat.vcf.output.tableG200.rds")
HVYTYDRX2_G200 <- readRDS("HVYTYDRX2.SortedCat.vcf.output.tableG200.rds")
HWMMFDMXY_G200 <- readRDS("HWMMFDMXY.SortedCat.vcf.output.tableG200.rds")
Zeo_G200 <- readRDS("Zeocin.SortedCat.vcf.output.tableG200.rds")
PQ_CSS8_G200 <- readRDS("PQ_CSS8.SortedCat.vcf.output.tableG200.rds")
CSS15_G200 <- readRDS("Jan25_CSS15.SortedCat.vcf.output.tableG200.rds")
```

```{r}
NonCu_G200 <- rbind(H2O2_G200, HVYTYDRX2_G200,HWMMFDMXY_G200,Zeo_G200,PQ_CSS8_G200,CSS15_G200)

dir()
MQC <- read.csv("MQC_Annotated_REVISED.csv")
MQC %>% select(Pool, PoolID, Dataset = Library, Parent, Bulk, Rep) -> MQC_Key

unique(NonCu_G200$Dataset)
NonCu_G200 %>% separate(Dataset, into = c("Pool", "Dataset"), sep = "_n01_") %>% mutate(Dataset = gsub(".fastq", "", Dataset)) -> NonCu_G200_reconfig

NonCu_G200_reconfig %>% merge(MQC_Key) -> NonCu_G200_MQC

saveRDS(NonCu_G200_MQC, file = "NonCu_G200_MQC.rds")
```

```{r}
MQC_Key %>% filter(Parent != "AIG", Parent != "AIG?", Bulk != "Freeze") %>%
  select(-Dataset, -Rep) %>% distinct() %>%
  mutate(CSS1 = grepl("1", Parent), CSS8 = grepl("8", Parent), CSS15 = grepl("2", Parent)) %>%
  pivot_longer(starts_with("CSS"), names_to = "CSS") %>%
  filter(value == TRUE) %>%
  pivot_wider(names_from = Bulk, values_from = Pool) -> PoolsByCondition

PoolsByCondition %>% select(-PoolID, -value) %>%
  pivot_longer(-c(Parent, CSS)) %>%
  na.omit() %>%
  mutate(name = gsub("CuSO4", "Copper", name)) -> PivotPools

for(i in unique(PivotPools$name)){
  print(i)
  PivotPools %>% filter(name == i) %>%
    select(value) -> PoolsToUse
  
  NonCu_G200_MQC %>% filter(Pool %in% PoolsToUse$value) -> stuff

  print(unique(PoolsToUse$value))
}

NonCu_G200_MQC %>% filter()
```

Looking at log ratios

```{r}
Fluc_G200 <- readRDS("Fluc2025G200.rds")
Fluc_Unsmoothed <- readRDS("Fluc2025_called_ex.rds")

Fluc_G200 %>% pivot_wider(names_from = Allele, values_from = SmoothCount) -> FlucLogOdds

FlucLogOdds %>% unnest() %>% mutate(logOdds = log(Wine/Oak)) %>%
  distinct() %>%
  filter(grepl("D", Dataset)) %>%
  separate(Dataset, into = c("Day", "Parent", "Bulk", "Rep"), sep = "_") -> FlucSmoothedPlot

Fluc_Unsmoothed %>% pivot_wider(names_from = Allele, values_from = Reads) %>%
  unnest() %>% mutate(logOdds = log(Wine/Oak)) %>%
  distinct() %>%
  filter(grepl("D", Dataset)) %>%
  separate(Dataset, into = c("Day", "Parent", "Bulk", "Rep"), sep = "_") -> FlucUnSmoothedPlot

################################################################################

FlucSmoothedPlot %>% mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16, 1000))))) %>%
  ggplot(aes(x = POS, y = logOdds, color = Parent, linetype = Rep)) + geom_line() +
  facet_grid(~CHROM, space = "free", scales = "free") +
  theme(legend.position = "bottom") -> Smoothed

FlucUnSmoothedPlot %>% mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16, 1000))))) %>%
  ggplot(aes(x = POS, y = logOdds, color = Parent, linetype = Rep)) + geom_point(shape = 1, size = 0.2) +
  facet_grid(~CHROM, space = "free", scales = "free") +
  theme(legend.position = "none") -> Unsmoothed

cowplot::plot_grid(Unsmoothed, Smoothed, ncol = 1)

```
```{r}
CSS15_G200 <- readRDS("Jan25_CSS15.SortedCat.vcf.output.tableG200.rds")
CSS15_Unsmoothed <- readRDS("Jan25_CSS15.SortedCat.vcf.output.table_called_ex.rds")

CSS15_Unsmoothed %>% pivot_wider(names_from = Allele, values_from = Reads) %>%
  unnest() %>% mutate(logOdds = log(Wine/Oak)) %>%
  distinct() %>%
  filter(grepl("D", Dataset)) %>%
  separate(Dataset, into = c("Pool", "Extra", "Parent", "Bulk", "Rep", "Fastq"), sep = "_") -> CSS15_UnSmoothedPlot


CSS15_G200 %>% pivot_wider(names_from = Allele, values_from = SmoothCount) %>%
  unnest() %>% mutate(logOdds = log(Wine/Oak)) %>%
  distinct() %>%
  separate(Dataset, into = c("Pool", "Extra", "Parent", "Bulk", "Rep", "Fastq"), sep = "_") %>%
  filter(Bulk == "D") -> CSS15_SmoothedPlot

CSS15_SmoothedPlot %>% filter(Bulk == "D") %>% 
  mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16, 1000))))) %>%
  filter(grepl("undetermined", Parent) == FALSE) %>%
  ggplot(aes(x = POS, y = logOdds, color = Parent, linetype = Rep)) + geom_line() +
  facet_grid(~CHROM, space = "free", scales = "free") +
    scale_color_manual(values = c("darkorange", "maroon")) +
  theme(legend.position = "bottom") -> Smoothed15

CSS15_UnSmoothedPlot%>% filter(Bulk == "D") %>% 
  mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16, 1000))))) %>%
  filter(grepl("undetermined", Parent) == FALSE) %>%
  ggplot(aes(x = POS, y = logOdds, color = Parent, linetype = Rep)) + geom_point(shape = 1, size = 0.2) +
  facet_grid(~CHROM, space = "free", scales = "free") +
  scale_color_manual(values = c("darkorange", "maroon")) +
  theme(legend.position = "none") -> Unsmoothed15

cowplot::plot_grid(Unsmoothed15, Smoothed15, ncol = 1)

CSS15_UnSmoothedPlot%>% filter(Bulk == "D", CHROM %in% c("III","XIII", "XV")) %>% 
  mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16, 1000))))) %>%
  filter(grepl("undetermined", Parent) == FALSE) %>%
  ggplot(aes(x = POS, y = logOdds, color = Parent, linetype = Rep)) + geom_point(shape = 1, size = 0.8, alpha = 0.3) +
  facet_grid(~CHROM, space = "free", scales = "free") +
  scale_color_manual(values = c("darkorange", "maroon")) +
  theme(legend.position = "none") -> zoomedin

CSS15_UnSmoothedPlot %>% filter(Bulk == "D", CHROM %in% c("III","XIII", "XV")) %>% 
  mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16, 1000))))) %>%
  filter(grepl("undetermined", Parent) == FALSE) %>%
  mutate(WGS_Coverage = Wine+Oak) %>%
  ggplot(aes(x = POS, y = WGS_Coverage, color = Parent, linetype = Rep)) + geom_line(alpha = 0.2)+
  facet_grid(~CHROM, space = "free", scales = "free") +
  scale_color_manual(values = c("darkorange", "maroon")) +
  theme(legend.position = "none") -> zoomedincoverage

cowplot::plot_grid(zoomedin, zoomedincoverage, ncol = 1)


CSS15_UnSmoothedPlot%>% filter(Bulk == "D", CHROM == "XIII") %>% 
  mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16, 1000))))) %>%
  filter(grepl("undetermined", Parent) == FALSE) %>%
  ggplot(aes(x = POS, y = logOdds, color = Parent, linetype = Rep)) + geom_point(shape = 1, size = 0.5) +
  geom_linerange(aes(xmin = 554793, xmax = 556475, y = 3),color = "black", size = 2) +
  geom_linerange(aes(xmin = (554793 - 1000 + 321), xmax = (554793 - 1000 + 1479), y = 1.5),color = "turquoise", size = 2) +
  geom_vline(aes(xintercept = 554793 - 1000 + 835), linetype = "dashed", color = "red") +
  geom_vline(aes(xintercept = 554793 - 1000 + 1034), linetype = "dashed", color = "red") +
  geom_vline(aes(xintercept = 554793 - 1000 + 1362), linetype = "dashed", color = "blue") +
  geom_vline(aes(xintercept = 554793 - 1000 + 1394), linetype = "dashed", color = "blue") +

  facet_grid(~CHROM, space = "free", scales = "free") +
  xlim(554000, 557500) +
  scale_color_manual(values = c("darkorange", "#64fDD8")) + 
  theme_bw() +
  theme(legend.position = "none")
```

# Running GLM for each

```{r}
# PoolsByCondition
# 
# cybrBSA::glm_cb2_short()
# Fluc_G200

Fluc_G200 %>% separate(Dataset, into = c("Day", "Parent", "Bulk", "Rep"), sep = "_") -> Fluc_Almost

Fluc_Almost %>% filter(Parent %in% c(11,12)) %>% mutate_if(is.character,as.factor)-> CSS1
Fluc_Almost %>% filter(Parent %in% c(17,18))  %>% mutate_if(is.character,as.factor)-> CSS8

contrasts(CSS1$Parent) <- c(0.5, -0.5)
contrasts(CSS8$Parent) <- c(0.5, -0.5)

contrasts(CSS1$Bulk)
contrasts(CSS8$Bulk)

CSS1 %>% na.omit() %>% 
  filter(CHROM %in% c("M", "I") == FALSE) %>%
  group_by(CHROM, POS) %>%
  # mutate_if(is.character, as.factor) %>%
  summarize(summary = glm_cb2_short(Allele = Allele,
                             Bulk = Bulk,
                             Parent = Parent,
                             
                             W = SmoothCount,
                             formula = "Allele ~ Bulk * Parent",
                             outputlength = 4),
            #MAKE SURE THIS IS THE SAME LENGTH AS OUTPUT LENGTH
            Factor = (c("Intercept", "Bulk", "Parent", "Interaction"))) -> processed_glm_all_Fluc_CSS1

CSS8 %>% na.omit() %>% 
  filter(CHROM %in% c("M", "VIII") == FALSE) %>%
  group_by(CHROM, POS) %>%
  # mutate_if(is.character, as.factor) %>%
  summarize(summary = glm_cb2_short(Allele = Allele,
                             Bulk = Bulk,
                             Parent = Parent,
                             
                             W = SmoothCount,
                             formula = "Allele ~ Bulk * Parent",
                             outputlength = 4),
            #MAKE SURE THIS IS THE SAME LENGTH AS OUTPUT LENGTH
            Factor = (c("Intercept", "Bulk", "Parent", "Interaction"))) -> processed_glm_all_Fluc_CSS8


saveRDS(processed_glm_all_Fluc_CSS1, file = "processed_glm_all_Fluc_CSS1.rds")

saveRDS(processed_glm_all_Fluc_CSS8, file = "processed_glm_all_Fluc_CSS8.rds")

```

```{r}
processed_glm_all_Fluc_CSS1 <- readRDS("processed_glm_all_Fluc_CSS1.rds")
processed_glm_all_Fluc_CSS8 <- readRDS("processed_glm_all_Fluc_CSS8.rds")
```

```{r}
processed_glm_all_Fluc_CSS1 %>% filter(Factor != "Intercept") %>% 
  mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16,1000))))) %>%
  ggplot(aes(x = POS, y = abs(summary), color = Factor)) + geom_line() +
  facet_grid(~CHROM, scales = "free", space = "free") + theme(legend.position = "bottom")
```

```{r}
processed_glm_all_Fluc_CSS8 %>% filter(Factor != "Intercept") %>% 
    mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16,1000))))) %>%
  ggplot(aes(x = POS, y = abs(summary), color = Factor)) + geom_line() +
  facet_grid(~CHROM, scales = "free", space = "free") + theme(legend.position = "bottom")
```


```{r}
processed_glm_all_Fluc_CSS1 %>% mutate(CSS = "I") -> temp

processed_glm_all_Fluc_CSS8 %>% mutate(CSS = "VIII") %>%
  rbind(temp) %>%
  filter(Factor != "Intercept") %>% 
  mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16,1000))))) %>%
  ggplot(aes(x = POS, y = abs(summary), color = Factor)) + geom_line() +
  facet_grid(CSS~CHROM, scales = "free", space = "free") + theme(legend.position = "bottom")

processed_glm_all_Fluc_CSS8 %>% mutate(CSS = "VIII") %>%
  rbind(temp) %>%
  filter(Factor != "Intercept", CHROM == "VII") %>% 
  mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16,1000))))) %>%
  ggplot(aes(x = POS, y = abs(summary), color = CSS)) + geom_line() +
  geom_vline(aes(xintercept = 4.78e5)) + #locating the peak
  #geom_vline(aes(xintercept = 693097)) + #MDR1, not it
  facet_grid(Factor~CHROM, scales = "free", space = "free") + 
  theme(legend.position = "bottom",
        axis.text.x = element_text())      

```

What interacts with ERG11 (on chr 8)?

```{r}
ERG11_Interactors_SGD <- read.table("C://Users/cassa/Downloads/ERG11_genetic_interactions.txt", sep = "\t", header = TRUE) 

SGD_ORFs <- read.csv("C:/Users/cassa/Documents/GitHub/cybrBSA/TestFiles//SGD_ORFs.csv")

SGD_ORFs %>% filter(Gene.chromosome.primaryIdentifier == "chrVII") %>%
  filter(Gene.symbol %in% ERG11_Interactors_SGD$Interactor.1) %>% mutate(Interactor.1 = Gene.symbol) %>%
  merge(ERG11_Interactors_SGD) %>%
  ggplot(aes(x = Gene.chromosomeLocation.start, y = -log(P.value), color = SGA.score)) + geom_point() +
  theme(legend.position = "bottom") + ggtitle("Potential ERG11 Interactors")

SGD_ORFs %>% filter(Gene.chromosome.primaryIdentifier == "chrVII") %>%
  filter(Gene.chromosomeLocation.start > 4.7e05, Gene.chromosomeLocation.start < 4.8e05)
```


## Identifying Cutoffs for Experiments

```{r}

Fluc_G200 %>% separate(Dataset, into = c("Day", "Parent", "Bulk", "Rep"), sep = "_") -> Fluc_Almost

Fluc_Almost %>% filter(Parent %in% c(11,12)) %>% mutate_if(is.character,as.factor)-> CSS1
Fluc_Almost %>% filter(Parent %in% c(17,18))  %>% mutate_if(is.character,as.factor)-> CSS8

contrasts(CSS1$Parent) <- c(0.5, -0.5)
contrasts(CSS8$Parent) <- c(0.5, -0.5)

contrasts(CSS1$Bulk)
contrasts(CSS8$Bulk)

CSS1 %>% na.omit() %>% 
  filter(Bulk == "D", CHROM %in% c("M", "I", "III") == FALSE) %>% #CHANGE THIS FOR FIXED CHROM EACH TIME
  group_by(CHROM, POS) %>%
  pivot_wider(names_from = Allele, values_from = SmoothCount) %>% unnest() %>%
  mutate(label = paste(CHROM, POS, sep = "_")) %>%
  group_by(Parent) %>%
  summarize(Selected = sample(label),
            Unselected = sample(label),
            Oak = Oak,
            Wine = Wine,
            Parent = Parent) %>%
  pivot_longer(cols = c(Selected, Unselected), names_to = "Bulk", values_to = "NewPOS") %>%
  separate(NewPOS, into = c("CHROM", "POS"), sep = "_") %>%
  pivot_longer(cols = c(Oak, Wine), names_to = "Allele", values_to = "SmoothCount") %>%
  mutate(Allele = as.factor(Allele), Bulk = as.factor(Bulk), Parent = as.factor(Parent)) -> rd_shuffled

contrasts(rd_shuffled$Parent) <- c(0.5, -0.5)

rd_shuffled %>% 
  group_by(CHROM, POS) %>%
  # mutate_if(is.character, as.factor) %>%
  summarize(summary = glm_cb2_short(Allele = Allele,
                             Bulk = Bulk,
                             Parent = Parent,
                             
                             W = SmoothCount,
                             formula = "Allele ~ Bulk * Parent",
                             outputlength = 4),
            #MAKE SURE THIS IS THE SAME LENGTH AS OUTPUT LENGTH
            Factor = (c("Intercept", "Bulk", "Parent", "Interaction"))) -> perm_glm_all_Fluc_CSS1

CSS8 %>% na.omit() %>% 
  filter(Bulk == "D", CHROM %in% c("M", "VIII", "III") == FALSE) %>% #CHANGE THIS FOR FIXED CHROM EACH TIME
  group_by(CHROM, POS) %>%
  pivot_wider(names_from = Allele, values_from = SmoothCount) %>% unnest() %>%
  mutate(label = paste(CHROM, POS, sep = "_")) %>%
  group_by(Parent) %>%
  summarize(Selected = sample(label),
            Unselected = sample(label),
            Oak = Oak,
            Wine = Wine,
            Parent = Parent) %>%
  pivot_longer(cols = c(Selected, Unselected), names_to = "Bulk", values_to = "NewPOS") %>%
  separate(NewPOS, into = c("CHROM", "POS"), sep = "_") %>%
  pivot_longer(cols = c(Oak, Wine), names_to = "Allele", values_to = "SmoothCount") %>%
  mutate(Allele = as.factor(Allele), Bulk = as.factor(Bulk), Parent = as.factor(Parent)) -> rd_shuffled

contrasts(rd_shuffled$Parent) <- c(0.5, -0.5)

rd_shuffled %>% 
  group_by(CHROM, POS) %>%
  # mutate_if(is.character, as.factor) %>%
  summarize(summary = glm_cb2_short(Allele = Allele,
                             Bulk = Bulk,
                             Parent = Parent,
                             
                             W = SmoothCount,
                             formula = "Allele ~ Bulk * Parent",
                             outputlength = 4),
            #MAKE SURE THIS IS THE SAME LENGTH AS OUTPUT LENGTH
            Factor = (c("Intercept", "Bulk", "Parent", "Interaction"))) -> perm_glm_all_Fluc_CSS8
```


```{r}
perm_glm_all_Fluc_CSS1 %>% na.omit() %>% group_by(Factor) %>%
  summarize(quantile(abs(summary), 0.95)) -> Quant_CSS1_Fluconazole

perm_glm_all_Fluc_CSS8 %>% na.omit() %>% group_by(Factor) %>%
  summarize(quantile(abs(summary), 0.95)) -> Quant_CSS8_Fluconazole

saveRDS(Quant_CSS1_Fluconazole, file = "Quant_CSS1_Fluconazole.rds")
saveRDS(Quant_CSS8_Fluconazole, file = "Quant_CSS8_Fluconazole.rds")

#cutoff ends up being 2 for intercept and 1.76 for all others
```
```{r}
iris %>% ggplot(aes(x = Sepal.Length, y = Sepal.Width, colour = Species, fill = Species)) + 
  geom_smooth(method = "lm") +
  geom_point()
```


