---
title: "Fluconazole2025"
author: "Cassandra Buzby"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(ggplot2)
require(tidyr)
require(dplyr)
# require(reshape2)
# require(cowplot)
# require(data.table)
# 
# require(doParallel)
# require(RColorBrewer)
# require(scales)
# require(circlize) 
# require(stringr)
# require(ggrepel)

#require(cybrBSA)
#require(lme4)

ggplot2::theme_set(theme_minimal() + theme(text = element_text(size = 10)) +
                     theme(#axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()))
```


```{r}
processed_glm_all_Fluc_CSS1 <- readRDS("processed_glm_all_Fluc_CSS1.rds")
processed_glm_all_Fluc_CSS8 <- readRDS("processed_glm_all_Fluc_CSS8.rds")

ERG11_Interactors_SGD <- read.table("C://Users/cassa/Downloads/ERG11_genetic_interactions.txt", sep = "\t", header = TRUE) 

SGD_ORFs <- read.csv("C:/Users/cassa/Documents/GitHub/cybrBSA/TestFiles//SGD_ORFs.csv")

```

```{r, warning = FALSE, message = FALSE}
processed_glm_all_Fluc_CSS1 %>% filter(Factor != "Intercept") %>% 
  mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16,1000))))) %>%
  ggplot(aes(x = POS, y = abs(summary), color = Factor)) + geom_line() +
  facet_grid(~CHROM, scales = "free", space = "free") + theme(legend.position = "bottom")
```

```{r, warning = FALSE, message = FALSE}
processed_glm_all_Fluc_CSS8 %>% filter(Factor != "Intercept") %>% 
    mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16,1000))))) %>%
  ggplot(aes(x = POS, y = abs(summary), color = Factor)) + geom_line() +
  facet_grid(~CHROM, scales = "free", space = "free") + theme(legend.position = "bottom")
```


```{r}
processed_glm_all_Fluc_CSS1 %>% mutate(CSS = "I") -> temp

processed_glm_all_Fluc_CSS8 %>% mutate(CSS = "VIII") %>%
  rbind(temp) %>%
  filter(Factor != "Intercept") %>% 
  mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16,1000))))) %>%
  ggplot(aes(x = POS, y = abs(summary), color = Factor)) + geom_line() +
  facet_grid(CSS~CHROM, scales = "free", space = "free") + theme(legend.position = "bottom")

processed_glm_all_Fluc_CSS8 %>% mutate(CSS = "VIII") %>%
  rbind(temp) %>%
  filter(Factor != "Intercept", CHROM == "VII") %>% 
  mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16,1000))))) %>%
  ggplot(aes(x = POS, y = abs(summary), color = CSS)) + geom_line() +
  geom_vline(aes(xintercept = 4.78e5)) + #locating the peak
  #geom_vline(aes(xintercept = 693097)) + #MDR1, not it
  facet_grid(Factor~CHROM, scales = "free", space = "free") + 
  theme(legend.position = "bottom",
        axis.text.x = element_text()) +
  scale_color_manual(values = c("steelblue", "darkorange"))

```

```{r}
processed_glm_all_Fluc_CSS8 %>% mutate(CSS = "VIII") %>%
  rbind(temp) %>%
  filter(Factor != "Intercept") %>% 
  mutate(CHROM = factor(CHROM, levels = as.character(as.roman(c(1:16,1000))))) %>%
  ggplot(aes(x = POS, y = abs(summary), color = CSS)) + geom_line() +
  geom_hline(yintercept = 1.76, linetype = "dashed") +
  facet_grid(Factor~CHROM, scales = "free", space = "free") + 
  theme(legend.position = "bottom",
        axis.text.x = element_blank()) +
  scale_color_manual(values = c("steelblue", "darkorange"))
```

What interacts with ERG11 (on chr 8)?

```{r, warning = FALSE, message = FALSE}

SGD_ORFs %>% filter(Gene.chromosome.primaryIdentifier == "chrVII") %>%
  filter(Gene.symbol %in% ERG11_Interactors_SGD$Interactor.1) %>% mutate(Interactor.1 = Gene.symbol) %>%
  merge(ERG11_Interactors_SGD) %>%
  ggplot(aes(x = Gene.chromosomeLocation.start, y = SGA.score, color = Interactor.1)) + geom_point(aes(
             size = -log(P.value)), shape = 1) + 
  geom_text_repel(aes(label = Interactor.1), size = 2, alpha = 0.6) +
  theme(legend.position = "bottom", axis.text.x = element_text()) + ggtitle("Potential ERG11 Interactors on Chr VII") + guides(color = "none")


SGD_ORFs %>% filter(Gene.chromosome.primaryIdentifier == "chrVII") %>%
  filter(Gene.chromosomeLocation.start > 4.7e05, Gene.chromosomeLocation.start < 4.8e05)
```

Note: Permutation cutoff ends up being 2 for intercept and 1.76 for all others
