---
title: "Figure Chr VII"
author: "Cassandra Buzby"
date: "9/30/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Load packages
library(ggplot2)
library(tidyr)
#library(tidyverse)
library(reshape2)
library(cowplot)
library(dplyr)

library(foreach)
library(doParallel)

ggplot2::theme_set(theme_light())
#ggplot2::theme_set(theme_bw())


CBchromPalette <- c("#F26430", "#0A369D", "#7EA3CC","#FF9F1C", "#C14953","#92DCE5", "#8FC93A","#4C4C47", 
                   "#F26430", "#0A369D", "#7EA3CC","#FF9F1C", "#C14953","#92DCE5", "#8FC93A","#4C4C47",
                  "#F26430", "#0A369D", "#7EA3CC")


library("QTLseqr")

```

Dependencies

```{r}
WineIFluc_D <- readRDS("RdataFiles/WineIFluc_D.rds")
OakIFluc_B <- readRDS("RdataFiles/OakIFluc_B.rds")
OakIDilute_B <- readRDS("RdataFiles/OakIDilute_B.rds")
WineIDilute_BD <- readRDS("RdataFiles/WineIDilute_BD.rds")
WineIDilute_B <- readRDS("RdataFiles/WineIDilute_B.rds")
WineIDilute_C <- readRDS("RdataFiles/WineIDilute_C.rds")

WineIDilute_BD %>% group_by(Index) %>% summarize(absmax = max(abs(bulk_Zprime)),
                                                 abs_95 = quantile(abs(bulk_Zprime), 0.975),
                                                 group = "between",
                                                 bulk = "dilute",
                                                 Sample = "WineD_BD_Max")-> WineD_BD_Max

WineIDilute_B %>% group_by(Index) %>% summarize(absmax = max(abs(bulk_Zprime)),
                                                 abs_95 = quantile(abs(bulk_Zprime), 0.975),
                                                 group = "within",
                                                 bulk = "dilute",
                                                 Sample = "WineD_B_Max")-> WineD_B_Max

OakIFluc_B %>% group_by(Index) %>% summarize(absmax = max(abs(bulk_Zprime)),
                                                 abs_95 = quantile(abs(bulk_Zprime), 0.975),
                                                 group = "within",
                                                 bulk = "fluconazole",
                                                 Sample = "OakF_B_Max")-> OakF_B_Max
WineIFluc_D %>% group_by(Index) %>% summarize(absmax = max(abs(bulk_Zprime)),
                                                 abs_95 = quantile(abs(bulk_Zprime), 0.975),
                                                 group = "within",
                                                 bulk = "fluconazole",
                                                 Sample = "WineF_D_Max")-> WineF_D_Max
WineIDilute_C %>% group_by(Index) %>% summarize(absmax = max(abs(bulk_Zprime)),
                                                 abs_95 = quantile(abs(bulk_Zprime), 0.975),
                                                 group = "within",
                                                 bulk = "dilute",
                                                 Sample = "WineD_C_Max")-> WineD_C_Max
OakIDilute_B %>% group_by(Index) %>% summarize(absmax = max(abs(bulk_Zprime)),
                                                 abs_95 = quantile(abs(bulk_Zprime), 0.975),
                                                 group = "within",
                                                 bulk = "dilute",
                                                 Sample = "OakD_B_Max")-> OakD_B_Max

between_max <- mean(WineD_BD_Max$absmax)
between_95 <- mean(WineD_BD_Max$abs_95)
within_max <- mean(WineD_B_Max$absmax)
within_95 <- mean(WineD_B_Max$abs_95)

MaxVals <- rbind(OakD_B_Max, WineD_C_Max,WineF_D_Max,OakF_B_Max,WineD_B_Max,WineD_BD_Max)

MaxVals %>% ggplot(aes(x = absmax, group = Sample, color = bulk, linetype = group)) + 
   geom_vline(xintercept = c(between_95), linetype = "dashed", size = 0.8) +
    geom_vline(xintercept = c(between_max), size = 0.8) +
  geom_density(size = 0.8) +
  geom_density(aes(x = abs_95, group = Sample, linetype = group), alpha = 0.2, fill = "gray", size = 0.8) +
  ggtitle("Distribution of Max (white) and 95% Max (gray)")


# WineD_BD_Max %>% ggplot(aes(x = absmax)) + geom_density(fill = "red", alpha = 0.2, size = 1) + 
#   geom_density(aes(x = abs_95), fill = "gray", alpha = 0.2, size = 1) +
#   geom_density(data = Wine_B_Max, aes(x = absmax), fill = "navyblue", 
#                alpha = 0.2, size = 1, linetype = "dashed") +
#   geom_density(data = Wine_B_Max, aes(x = abs_95), fill = "gray", 
#                alpha = 0.2, size = 1, linetype = "dashed")+
#   ggtitle("Comparison of Max (colored) and 95% (gray) of B vs BxD")

between_max <- mean(WineD_BD_Max$absmax)
between_95 <- mean(WineD_BD_Max$abs_95)
within_max <- mean(WineD_B_Max$absmax)
within_95 <- mean(WineD_B_Max$abs_95)
```


## Just Chr 7 for presentation

```{r}
between_95 <- mean(WineD_BD_Max$abs_95)
between_max <- mean(WineD_BD_Max$absmax)

load("RdataFiles/CSSI_F_ZScores_GLM_allexcl.Rdata")

CSSI_F_ZScores_GLM %>% filter(CHROM == "VII" | CHROM == "XIII") %>% ggplot(aes(x = POS, y = Bulk_Zprime)) + 
  geom_hline(yintercept = c(-between_95, between_95), linetype = "dashed", size = 0.8) +
    geom_hline(yintercept = c(-between_max, between_max), size = 0.8) +
  geom_hline(yintercept = c(-1.96, 1.96), color = "gray")+
  geom_point(color = "#345F6F", size = 0.2, alpha = 0.8) + 
  geom_point(aes(x = POS, y = Parent_Zprime), color = "#FFB05C", alpha= 0.8, size = 0.2) +
  geom_point(aes(x = POS, y = Day_Zprime), color = "gray", alpha= 0.8, size = 0.2) +
  geom_point(aes(x = POS, y = Interaction_Zprime), color = "#D7335C", alpha= 0.8, size = 0.2) +
  scale_x_continuous(breaks = seq(from = 0, to = max(CSSI_F_ZScores_GLM$POS), by = 1e5), name = "Genomic Position") +
  facet_grid(~CHROM, scales = "free_x", space = "free_x") + theme_minimal() +
  
  ggtitle("CSSI Fluconazole | Comparison of Smoothed Z scores") + theme(legend.position = "none", axis.text.x=element_blank(),
        axis.ticks.x=element_blank()) + 
  xlab("Genomic Position") + ylab("Oak  <--    Z Score  -->  Wine")

```