---
title: "All Traits Figures"
author: "Cass"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Load packages
require(ggplot2)
require(tidyr)
require(dplyr)
require(reshape2)
require(cowplot)
require(data.table)

require(doParallel)
require(RColorBrewer)
require(scales)
require(circlize) 
require(stringr)
require(ggrepel)

require(cybrBSA)
require(lme4)

ggplot2::theme_set(theme_minimal() + theme(text = element_text(size = 10)) +
                     theme(#axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()))
```

## Load in data

```{r}
Aug24_CSS8_glm_day <- readRDS("Aug24_CSS8_glm_day.rds") %>% mutate(CSS = 8) %>% mutate(Sel = gsub("C", "Cyclohex", Sel)) %>%
                                                                                mutate(Sel = gsub("E", "Ethanol", Sel)) %>%
                                                                                mutate(Sel = gsub("H", "H2O2", Sel)) %>% mutate(Selection = Sel)

Aug24_CSS1_glm_day <- readRDS("Aug24_CSS1_glm_day.rds") %>% mutate(CSS = 1) %>% mutate(Sel = gsub("C", "Cyclohex", Sel)) %>%
                                                                                mutate(Sel = gsub("E", "Ethanol", Sel)) %>%
                                                                                mutate(Sel = gsub("H", "H2O2", Sel)) %>% mutate(Selection = Sel)

Fluc_CSS1_glm <- readRDS("C:/Users/Cassandra/Documents/R_FileTransfer/StandardGLM/HGVMVDRX2norep_CSS1_glm_all.rds") %>% 
  mutate(zscore = Summary, label = Factor, Selection = "Fluconazole") %>%
  select(-Summary, -Factor) %>%
  na.omit() %>% mutate(CSS = 1)

Fluc_CSS8_glm <- readRDS("C:/Users/Cassandra/Documents/R_FileTransfer/StandardGLM/E_HVYTYDRX2_Fluc_CSS8_glm_all.rds") %>% 
  mutate(zscore = Summary, label = Factor, Selection = "Fluconazole") %>%
  select(-Summary, -Factor) %>%
  na.omit() %>% mutate(CSS = 8)

CuSO4_CSS8_glmer_1byRep <- readRDS("CuSO4_CSS8_glmer_1byRepG.rds") %>% mutate(Selection = "Copper", CSS = 8)
CuSO4_CSS1_glmer_1byRep <- readRDS("CuSO4_CSS1_glmer_1byRepG.rds") %>% mutate(Selection = "Copper", CSS = 1)

Zeo_CSS1_glm <- readRDS("C:/Users/Cassandra/Documents/R_FileTransfer/StandardGLM/HKTMWDRX2_Zeo_CSS1_glm_all_noreps.rds") %>%
  mutate(zscore = Summary, label = Factor, Selection = "ZeocinA") %>%
  select(-Summary, -Factor) %>%
  na.omit() %>% mutate(CSS = 1)

Zeo_CSS8_glm <- readRDS("C:/Users/Cassandra/Documents/R_FileTransfer/StandardGLM/Z_HJ5HKDRX3_CSS8_glm_all_noreps.rds") %>%
  mutate(zscore = Summary, label = Factor, Selection = "ZeocinB") %>%
  select(-Summary, -Factor) %>%
  na.omit() %>% mutate(CSS = 8)

Zeo_CSS1B_glm <- readRDS("C:/Users/Cassandra/Documents/R_FileTransfer/StandardGLM/Z_HJ5HKDRX3_CSS1_glm_all_noreps.rds") %>%
  mutate(zscore = Summary, label = Factor, Selection = "ZeocinB") %>%
  select(-Summary, -Factor) %>%
  na.omit() %>% mutate(CSS = 1)

```

```{r}
Aug24_CSS8_glm_day %>% rbind(Aug24_CSS1_glm_day) %>% select(-Sel) %>%
  rbind(Fluc_CSS1_glm) %>%
  rbind(Fluc_CSS8_glm) %>%
  rbind(CuSO4_CSS8_glmer_1byRep) %>%
  rbind(CuSO4_CSS1_glmer_1byRep) -> AllExp

AllExp %>% filter(label == "Bulk") %>% ggplot(aes(x = POS, y = zscore, color = CSS)) + geom_line() +
  facet_grid(Selection ~ CHROM, scales = "free", space = "free")

AllExp %>% filter(Selection == "Cyclohex",
                  label %in% c("Interaction", "Bulk")) %>% ggplot(aes(x = POS, y = zscore, color = CSS)) + geom_point(size = 0.3, alpha = 0.5) +
  facet_grid(label ~ CHROM, scales = "free", space = "free")

AllExp %>% filter(Selection == "Cyclohex",
                  label %in% c("Interaction")) %>% ggplot(aes(x = POS, y = zscore, color = CSS)) + geom_point(size = 0.3, alpha = 0.5) +
  facet_grid(label ~ CHROM, scales = "free", space = "free")

```
```{r}
AllExp %>% filter(label == "Interaction") %>% ggplot(aes(x = POS, y = zscore, color = factor(CSS))) + geom_line() +
  facet_grid(Selection ~ CHROM, scales = "free", space = "free") +
  theme(legend.position = "bottom")
```
Do cycloheximide interactions negatively correlate with bulk effects?

```{r}
AllExp %>% filter(Selection == "Cyclohex",
                  label %in% c("Interaction", "Bulk")) %>% 
  pivot_wider(names_from = label, values_from = zscore) %>%
  ggplot(aes(x = Bulk, y = Interaction, color = CSS)) + geom_point(size = 0.3, alpha = 0.5) 
```

```{r}
AllExp %>% filter(label %in% c("Interaction", "Bulk")) %>% 
  pivot_wider(names_from = label, values_from = zscore) %>%
  ggplot(aes(x = Bulk, y = Interaction)) + 
  geom_point(aes(color = Selection), size = 0.3, alpha = 0.01) +
  geom_smooth(method = "lm", color = "black") +
  facet_grid(Selection ~ CSS) +
  theme(legend.position = "none") +
  theme_bw()

```
```{r, fig.width=10, fig.height=6}

AllExp %>% filter(label == "Interaction") %>% ggplot() + 
    geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = -1, ymax = 1), alpha = 0.3, fill = "gray", color = "gray") +
  geom_line(aes(x = POS, y = zscore, color = factor(CSS))) +
  facet_grid(Selection ~ CHROM, scales = "free", space = "free") +
  scale_color_manual(values = c("black","skyblue2")) +
  ggtitle("Interaction Effects by Trait and Fixed Chromosome") +
  theme_bw() +  theme(legend.position = "bottom", axis.text.x = element_blank()) 


AllExp %>% filter(label == "Bulk") %>% ggplot() + 
      geom_rect(aes(xmin = -Inf, xmax = Inf, ymin = -1, ymax = 1), alpha = 0.3, fill = "gray", color = "gray") +
  geom_line(aes(x = POS, y = zscore, color = factor(CSS))) +
  facet_grid(Selection ~ CHROM, scales = "free", space = "free") +
  scale_color_manual(values = c("black","skyblue2")) +
  ggtitle("Bulk Effects by Trait and Fixed Chromosome") +
  theme_bw() +  theme(legend.position = "bottom", axis.text.x = element_blank()) 
```

Zeocin on its own to check

```{r}
rbind(Zeo_CSS1_glm, Zeo_CSS8_glm, Zeo_CSS1B_glm) -> zeo_all

zeo_all %>% filter(label != "Intercept") %>% ggplot(aes(x = POS, y = zscore, color = factor(CSS), linetype = Selection)) + geom_line() +
  facet_grid(label ~ CHROM, scales = "free", space = "free")
```

