---
title: "GLM vs GLMER"
author: "Cass"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Load packages
require(ggplot2)
require(tidyr)
require(dplyr)
require(reshape2)
require(cowplot)
require(data.table)

require(doParallel)
require(RColorBrewer)
require(scales)
require(circlize) 
require(stringr)
require(ggrepel)

require(cybrBSA)
require(lme4)

ggplot2::theme_set(theme_minimal() + theme(text = element_text(size = 10)) +
                     theme(#axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()))

ChromosomeScale <- data.frame(CHROM = factor(as.character(as.roman(1:16)),
                                             levels = as.character(as.roman(1:16))),
                              start = rep(1, 16),
                              end = c(.23,.81,.32, 1.53, .58, .27, 1.09, .56, .44, .75, .67, 1.08, .92, .78, 1.09, .95)*1000000) %>% 
  pivot_longer(c(start, end), names_to = "delete", values_to = "POS") %>%
  mutate(Summary = NA, Label = NA) %>% select(-delete)

ChromosomeScale$Start <- 30000
ChromosomeScale$End <- ChromosomeScale$POS - 30000

ChromosomeScale2 <- data.frame(CHROM = factor(as.character(as.roman(1:16)),
                                             levels = as.character(as.roman(1:16))),
                              start = rep(1, 16),
                              end = c(.23,.81,.32, 1.53, .58, .27, 1.09, .56, .44, .75, .67, 1.08, .92, .78, 1.09, .95)*1000000) %>% 
  pivot_longer(c(start, end), names_to = "delete", values_to = "POS") %>%
  mutate(summary = 0, label = "Bulk") %>% select(-delete)

# Loci to look at specifically

myloci <- data.frame(CHROM = c("V","V","IX", "III", "IV", "I", "III"),
                     POS = c(375215, 116167,389572, 198671, 46271, 203403, 260311),
                     name = c("FLO8", "URA3", "FLO11", "MAT", "HO", "FLO1", "TUP1"),
                     cat = c("Floc", "X", "Floc", "X", "X", "Floc", "Floc"))

## RANDOM NEW FUNCTIONS

subtract <- function(POS){
  return(max(POS) - min(POS))
}

findchange <- function(x){
  t <- length(x)
  diff <- x[t] - x[1]
  if(is.na(diff)){
    return(NA)
  }else if(diff == 0){
    return(0)
  }else{
    return(diff > 0)  
  }
}

findpeak <- function(x){
  t <- length(x)
  diff <- x[t] - x[1]
  return(diff)
}

  
cybr_weightedgauss <- function(myx){
  myy <- dnorm(1:length(myx), mean = length(myx)/2, sd = 10)
  return(weighted.mean(x = myx, y = myy, na.rm = TRUE))
} 


## Functions for GLM all and Permutation all

glm_cb2_all <- function(..., W, formula, numgroups = FALSE, outputlength = 8) {
  data <- list(...)
  
  #Ensure that there is a formula and W parameter
  if (is.null(W) || is.null(formula)) {
    stop("Weights (W) and formula must be provided")
  }
  #Set formula
  glm_formula <- as.formula(formula)
  #Ensure that formula works for the data provided
  if (!all(names(data) %in% all.vars(glm_formula))) {
    stop("One or more variables in the formula are not provided as arguments")
  }
  
  #########################
  for(i in all.vars(glm_formula)){
    if(length(unique(as.data.frame(data)[,i])) < 2){
      output <- rep(NA, outputlength)
      #print("Not enough levels within groups")
      
      return(output)
    }
  }
  
  glm_fit <- glm(glm_formula, data = as.data.frame(data), weights = W, family = binomial)
  
  output <- summary(glm_fit)$coefficients[c(((length(summary(glm_fit)$coefficients)*0)+1):
                                            ((length(summary(glm_fit)$coefficients)*0.25)),
                                            ((length(summary(glm_fit)$coefficients)*0.5)+1):
                                            ((length(summary(glm_fit)$coefficients)*0.75)))]

  
  if(length(output) == outputlength){
    return(output)
  }else{
    return(rep(NA, outputlength))
  }
  
} 

```

# Load Data

```{r}
rd_factor <- readRDS("rd_factorG.rds")

#Test if factor encodings are correct
contrasts(rd_factor$Background)
contrasts(rd_factor$Bulk)

rd_factor %>% filter(CHROM == "IX") -> test_IX

test_IX %>% filter(POS == 285202) -> test_df

#testing what went wrong
test_IX %>% filter(POS == 36103) -> test_df

```

# Make new function that saves AIC

```{r}
glm_fit <- glm(Allele ~ Bulk*Background, data = as.data.frame(test_df), weights = SmoothCount, 
        family = binomial)

glm_fit <- glmer(Allele ~ Bulk*Background + (1|Dataset), data = as.data.frame(test_df), weights = SmoothCount, 
        family = binomial)


glm_compare_error <- function (..., W, formula, numgroups = FALSE, outputlength = 4) 
{
    data <- list(...)
    if (is.null(W) || is.null(formula)) {
        stop("Weights (W) and formula must be provided")
    }
    glm_formula <- as.formula(formula)
    if (!all(names(data) %in% all.vars(glm_formula))) {
        stop("One or more variables in the formula are not provided as arguments")
    }
    for (i in all.vars(glm_formula)) {
        if (length(unique(as.data.frame(data)[, i])) < 2) {
            output <- rep(NA, outputlength + 3)
            return(output)
        }
    }
    glm_fit <- glm(glm_formula, data = as.data.frame(data), weights = W, 
        family = binomial)
    
    output <- summary(glm_fit)$coefficients[((length(summary(glm_fit)$coefficients) * 
            0.5) + 1):((length(summary(glm_fit)$coefficients) * 
            0.75))]
    
    errors <- c(summary(glm_fit)$aic,
                summary(glm_fit)$null.deviance,
                summary(glm_fit)$deviance)
    
    if (length(output) == outputlength & length(errors) == 3) {
        return(c(output, errors))
    }
    else {
        return(rep(NA, outputlength + 3))
    }
}

glmer_compare_error <- function (..., W, formula, numgroups = FALSE, outputlength = 4){
    data <- list(...)
    
    require(lme4)
    if (is.null(W) || is.null(formula)) {
        stop("Weights (W) and formula must be provided")
    }
    glm_formula <- as.formula(formula)
    if (!all(names(data) %in% all.vars(glm_formula))) {
        stop("One or more variables in the formula are not provided as arguments")
    }
    for (i in all.vars(glm_formula)) {
        if (length(unique(as.data.frame(data)[, i])) < 2) {
            output <- rep(NA, outputlength + 1)
            return(output)
        }
    }
    glm_fit <- glmer(glm_formula, data = as.data.frame(data), weights = W, 
        family = binomial)
    
    output <- summary(glm_fit)$coefficients[((length(summary(glm_fit)$coefficients) * 
            0.5) + 1):((length(summary(glm_fit)$coefficients) * 
            0.75))]
    
    errors <- c(summary(glm_fit)$AICtab[1])
    
    if (length(output) == outputlength & length(errors) == 1) {
        return(c(output, errors))
    }
    else {
        return(rep(NA, outputlength + 1))
    }
}
```

# Test on single one

```{r}
test_df %>% group_by(CHROM, POS) %>%
  summarize(stat = glm_compare_error(Allele = Allele, Background = Background, Bulk = Bulk,
                                     W = SmoothCount,
                                     formula = "Allele ~ Bulk*Background"),
            labels = c("cept", "Bulk", "Background", "Interaction",
                       "AIC", "NullDev", "ResidDev")) 

test_df %>%  group_by(CHROM, POS) %>%
  summarize(stat = glmer_compare_error(Allele = Allele, Background = Background, Bulk = Bulk, Rep = Dataset,
                                     W = SmoothCount, 
                                     formula = "Allele ~ Bulk*Background + (1 | Rep)"),
            labels = c("cept", "Bulk", "Background", "Interaction", 
                       "AIC")) 

```


# Run this on Chr IX

```{r}
test_IX %>% group_by(CHROM, POS) %>%
  summarize(stat = glm_compare_error(Allele = Allele, Background = Background, Bulk = Bulk,
                                     W = SmoothCount,
                                     formula = "Allele ~ Bulk*Background"),
            labels = c("cept", "Bulk", "Background", "Interaction",
                       "AIC", "NullDev", "ResidDev")) -> TestChr

test_IX %>% group_by(CHROM, POS) %>% 
  summarize(stat = glmer_compare_error(Allele = Allele, Background = Background, Bulk = Bulk, Rep = Dataset,
                                     W = SmoothCount, 
                                     formula = "Allele ~ Bulk*Background + (1 | Rep)"),
            labels = c("cept", "Bulk", "Background", "Interaction", 
                       "AIC")) -> TestChr_glmer

TestChr_glmer %>% na.omit()
```

# Compare AIC values

```{r}
TestChr %>% mutate(test = "glm") -> tempagain
TestChr_glmer %>% mutate(test = "glmer") %>%
  rbind(tempagain) -> Compare_IX

Compare_IX %>% na.omit() %>%
  pivot_wider(names_from = labels, values_from = stat) %>%
  ggplot(aes(x = AIC, color = test)) + geom_density()

################################################################################
Compare_IX %>% na.omit() %>%
  pivot_wider(names_from = c(test, labels), values_from = stat) -> Compare_IX_wide

Compare_IX_wide %>%
  ggplot(aes(x = glm_AIC, y = glmer_AIC)) + geom_point(alpha = 0.4) +
  geom_abline(slope = 1, intercept = 0, color = "skyblue")

Compare_IX_wide %>%
  ggplot(aes(x = glm_Bulk, y = glmer_Bulk)) + geom_point(alpha = 0.4)+
  geom_abline(slope = 1, intercept = 0, color = "skyblue")

Compare_IX_wide %>%
  ggplot(aes(x = glm_Interaction, y = glmer_Interaction)) + geom_point(alpha = 0.4)+
  geom_abline(slope = 1, intercept = 0, color = "skyblue")

Compare_IX_wide %>%
  ggplot(aes(x = glm_Background, y = glmer_Background)) + geom_point(alpha = 0.4)+
  geom_abline(slope = 1, intercept = 0, color = "skyblue")

  
```

```{r}
Compare_IX %>% pivot_wider(names_from = labels, values_from = stat) %>%
  ggplot(aes(x = Bulk, y = Interaction, color = test)) + geom_point(alpha = 0.4) +
  geom_smooth(method = "lm")

Compare_IX %>% pivot_wider(names_from = labels, values_from = stat) %>%
  ggplot(aes(x = Bulk, y = AIC, color = test)) + geom_point(alpha = 0.4) +
  geom_smooth(method = "lm")

Compare_IX %>% pivot_wider(names_from = labels, values_from = stat) %>%
  ggplot(aes(x = cept, y = AIC, color = test)) + geom_point(alpha = 0.4) +
  geom_smooth(method = "lm")

Compare_IX %>% pivot_wider(names_from = labels, values_from = stat) %>%
  ggplot(aes(x = Bulk, y = cept, color = test)) + geom_point(alpha = 0.4) +
  geom_smooth(method = "lm")
```

By Position

```{r}
Compare_IX %>% ggplot(aes(x = POS, y = stat, color = test)) + geom_point(alpha = 0.2) +
  facet_grid(rows = "labels", scales = "free")
```

