---
title: "MergedVCFs_ZivAIG_May24"
author: "Cassandra Buzby"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Load packages
require(ggplot2)
require(tidyr)
require(dplyr)
require(reshape2)
require(cowplot)
require(data.table)

require(doParallel)
require(RColorBrewer)
require(scales)
require(circlize) 
require(stringr)
require(ggrepel)

require(cybrBSA)
require(lme4)

ggplot2::theme_set(theme_minimal() + theme(text = element_text(size = 10)) +
                     theme(#axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()))

ChromosomeScale <- data.frame(CHROM = factor(as.character(as.roman(1:16)),
                                             levels = as.character(as.roman(1:16))),
                              start = rep(1, 16),
                              end = c(.23,.81,.32, 1.53, .58, .27, 1.09, .56, .44, .75, .67, 1.08, .92, .78, 1.09, .95)*1000000) %>% 
  pivot_longer(c(start, end), names_to = "delete", values_to = "POS") %>%
  mutate(Summary = NA, Label = NA) %>% select(-delete)

ChromosomeScale$Start <- 30000
ChromosomeScale$End <- ChromosomeScale$POS - 30000

ChromosomeScale2 <- data.frame(CHROM = factor(as.character(as.roman(1:16)),
                                             levels = as.character(as.roman(1:16))),
                              start = rep(1, 16),
                              end = c(.23,.81,.32, 1.53, .58, .27, 1.09, .56, .44, .75, .67, 1.08, .92, .78, 1.09, .95)*1000000) %>% 
  pivot_longer(c(start, end), names_to = "delete", values_to = "POS") %>%
  mutate(summary = 0, label = "Bulk") %>% select(-delete)

# Loci to look at specifically

myloci <- data.frame(CHROM = c("V","V","IX", "III", "IV", "I", "III"),
                     POS = c(375215, 116167,389572, 198671, 46271, 203403, 260311),
                     name = c("FLO8", "URA3", "FLO11", "MAT", "HO", "FLO1", "TUP1"),
                     cat = c("Floc", "X", "Floc", "X", "X", "Floc", "Floc"))



## Functions for GLM all and Permutation all

glm_cb2_all <- function(..., W, formula, numgroups = FALSE, outputlength = 8) {
  data <- list(...)
  
  #Ensure that there is a formula and W parameter
  if (is.null(W) || is.null(formula)) {
    stop("Weights (W) and formula must be provided")
  }
  #Set formula
  glm_formula <- as.formula(formula)
  #Ensure that formula works for the data provided
  if (!all(names(data) %in% all.vars(glm_formula))) {
    stop("One or more variables in the formula are not provided as arguments")
  }
  
  #########################
  for(i in all.vars(glm_formula)){
    if(length(unique(as.data.frame(data)[,i])) < 2){
      output <- rep(NA, outputlength)
      #print("Not enough levels within groups")
      
      return(output)
    }
  }
  
  glm_fit <- glm(glm_formula, data = as.data.frame(data), weights = W, family = binomial)
  
  output <- summary(glm_fit)$coefficients[c(((length(summary(glm_fit)$coefficients)*0)+1):
                                            ((length(summary(glm_fit)$coefficients)*0.25)),
                                            ((length(summary(glm_fit)$coefficients)*0.5)+1):
                                            ((length(summary(glm_fit)$coefficients)*0.75)))]

  
  if(length(output) == outputlength){
    return(output)
  }else{
    return(rep(NA, outputlength))
  }
  
} 


################################################################################
# No replicates, fix Parent
cybrPermute_cb2_all <- function(dataset, 
                                R = 0, perp = 1, outlength = 4, 
                                glmform = "Allele ~ Bulk * Parent", 
                                inputlabels = c("Intercept", "Bulk", "Parent", "Interaction")){
  start.time <- Sys.time()
    
  print("Make sure that dilute bulk is labeled aD")
  print(paste("Your labels are:", inputlabels))

    if(R > 0){ #INCLUDE REPLICATES
        dataset %>% 
        distinct() %>% ungroup() %>%
        group_by(CHROM, POS, Allele, Bulk, Rep, Parent) %>% 
        summarize(culprits = length((SmoothCount))) %>% 
        merge(dataset) %>% 
        filter(culprits == 1) %>% 
        ungroup() %>%
        distinct() %>% #THIS IS IMPORTANT
        pivot_wider(names_from = Allele, values_from = SmoothCount) -> newnewtest    
    }else{ #DO NOT INCLUDE REPLICATES
        dataset %>% 
        distinct() %>% ungroup() %>%
        group_by(CHROM, POS, Allele, Bulk, Parent) %>% 
        summarize(culprits = length((SmoothCount))) %>% 
        merge(dataset) %>% 
        filter(culprits == perp) %>% 
        ungroup() %>%
        distinct() %>% #THIS IS IMPORTANT
        pivot_wider(names_from = Allele, values_from = SmoothCount) -> newnewtest
    }
  
    #PERMUTE TWICE
  if(R > 0){
    newnewtest %>% filter(Bulk == "aD",
                          CHROM %in% c("I", "III", "V", "VIII", "M") == FALSE) %>% 
      select(CHROM, POS, Rep, 
             Parent, Oak, Wine) %>% 
      group_by(Parent) %>% mutate(Loc = paste(CHROM, POS)) %>%
      summarize(Parent = Parent, Rep = Rep, 
                Oak = Oak, Wine = Wine, Loc = sample(Loc)) %>%
      mutate(Bulk = "A") -> shuffled_DiluteA2
    
    newnewtest %>% filter(Bulk == "aD",
                          CHROM %in% c("I", "III", "V", "VIII", "M") == FALSE) %>% 
      select(CHROM, POS, 
             Rep, Parent, Oak, Wine) %>% 
      group_by(Parent) %>% mutate(Loc = paste(CHROM, POS)) %>%
      summarize(Parent = Parent, Rep = Rep,
                Oak = Oak, Wine = Wine, Loc = sample(Loc)) %>%
      mutate(Bulk = "B") -> shuffled_DiluteB2
    
  }else{
    newnewtest %>% filter(Bulk == "aD",
                          CHROM %in% c("I", "III", "V", "VIII", "M") == FALSE) %>% 
      select(CHROM, POS, Parent, Oak, Wine) %>% 
      group_by(Parent) %>% mutate(Loc = paste(CHROM, POS)) %>%
      summarize(Parent = Parent, Oak = Oak, Wine = Wine, Loc = sample(Loc)) %>%
      mutate(Bulk = "A") -> shuffled_DiluteA2
    
    newnewtest %>% filter(Bulk == "aD",
                          CHROM %in% c("I", "III", "V", "VIII", "M") == FALSE) %>% 
      select(CHROM, POS, Parent, Oak, Wine) %>% 
      group_by(Parent) %>% mutate(Loc = paste(CHROM, POS)) %>%
      summarize(Parent = Parent, Oak = Oak, Wine = Wine, Loc = sample(Loc)) %>%
      mutate(Bulk = "B") -> shuffled_DiluteB2
    
  }
    
    rbind(shuffled_DiluteA2, shuffled_DiluteB2) %>% pivot_longer(c(Oak, Wine), names_to = "Allele", values_to = "SmoothCount") -> shuffletoglm2
    
    #RUN THE GLM
    if(R > 0) {
      shuffletoglm2 %>% na.omit() %>%
      group_by(Loc) %>%
      mutate_if(is.character, as.factor) %>%
        summarize(Summary = glm_cb2_all(Allele = Allele,
                                 Bulk = Bulk,
                                 Parent = Parent,
                                 Rep = Rep,
                                 W = SmoothCount,
                                 formula = glmform,
                                outputlength = length(inputlabels)*2),
                Factor = rep(inputlabels, 2),
                d = c(rep("Effect", length(inputlabels)),
                      rep("Z", length(inputlabels)))) -> glmresult
    }else{
      shuffletoglm2 %>% na.omit() %>%
      #Original Script
      group_by(Loc) %>%
      mutate_if(is.character, as.factor) %>%
        summarize(Summary = glm_cb2_all(Allele = Allele,
                                 Bulk = Bulk,
                                 Parent = Parent,
                                 W = SmoothCount,
                                 formula = glmform,
                                outputlength = length(inputlabels)*2),
                Factor = rep(inputlabels, 2),
                d = c(rep("Effect", length(inputlabels)),
                      rep("Z", length(inputlabels)))) -> glmresult
    }
    
    
    end.time = Sys.time()
    print(end.time - start.time)
    return(glmresult)
}

cybrInputGATKTable2 <- function(Ziv_rawData, yeast = TRUE){

  require(dplyr)
  require(doParallel)
  require(foreach)

  HNGLCDRXY <- read.table(Ziv_rawData, header = TRUE)

  #Identify the unique values besides AD/DP/GQ/PL
  gsub(".AD", "",
       gsub(".GQ", "",
            gsub(".DP","",
                 gsub(".PL","",
                      colnames(select(HNGLCDRXY, -CHROM, -POS, -REF, -ALT)))))) %>% unique() -> Samples
  #i <- Samples[1]

  resultscdf <- foreach(i=Samples,.combine=rbind) %dopar% {
    mydf <- HNGLCDRXY %>% select(CHROM, POS, REF, ALT) %>% mutate(Dataset = i)
    AD <- select(HNGLCDRXY,matches(c(i), ignore.case = FALSE)) %>% select(., contains("AD"))
    GQ <- select(HNGLCDRXY,matches(c(i), ignore.case = FALSE)) %>% select(., contains("GQ"))
    DP <- select(HNGLCDRXY,matches(c(i), ignore.case = FALSE)) %>% select(., contains("DP"))
    PL <- select(HNGLCDRXY,matches(c(i), ignore.case = FALSE)) %>% select(., contains("PL"))
    cbind(mydf, AD , GQ , DP, PL) -> mydftotal
    colnames(mydftotal) <- c(colnames(mydf), "AD", "GQ", "DP", "PL")

    mydftotal %>% separate(AD, c('AD.REF','AD.ALT'), extra='drop') %>%
      separate(PL, c('PL.REF','PL.ALT'), extra='drop') %>%
      #Added 10/18/23:
      select(CHROM, POS,REF,ALT,Dataset,AD.REF,AD.ALT,GQ,DP,PL.REF,PL.ALT) -> mycdf

    mycdf %>% filter(grepl(",", ALT)) %>% 
      separate(ALT, c("A1", "A2"), extra = 'merge') %>%
      separate(AD.ALT, c("AD1", "AD2"), extra = 'merge') %>%
      separate(PL.ALT, c("P1", "P2"), extra = 'merge') %>%
      
      pivot_longer(c(A1, A2), names_to = "NumAlt", values_to = "ALT") %>%
      pivot_longer(c(AD1, AD2), names_to = "NumADAlt", values_to = "AD.ALT") %>%
      pivot_longer(c(P1, P2), names_to = "NumPL", values_to = "PL.ALT") %>%
      mutate(NumAlt = gsub("A", "", NumAlt),
             NumADAlt = gsub("AD", "", NumADAlt),
             NumPL = gsub("P", "", NumPL)) %>%
      filter(NumAlt == NumPL,
             NumPL == NumADAlt) %>%
      select(CHROM, POS,REF,ALT,Dataset,AD.REF,AD.ALT,GQ,DP,PL.REF,PL.ALT) -> doublecdf
    
    doublecdf %>% filter(grepl(",", ALT)) %>%
      separate(ALT, c("A1", "A2"), extra = 'merge') %>%
      separate(AD.ALT, c("AD1", "AD2"), extra = 'merge') %>%
      separate(PL.ALT, c("P1", "P2"), extra = 'merge') %>%
      
      pivot_longer(c(A1, A2), names_to = "NumAlt", values_to = "ALT") %>%
      pivot_longer(c(AD1, AD2), names_to = "NumADAlt", values_to = "AD.ALT") %>%
      pivot_longer(c(P1, P2), names_to = "NumPL", values_to = "PL.ALT") %>%
      mutate(NumAlt = gsub("A", "", NumAlt),
             NumADAlt = gsub("AD", "", NumADAlt),
             NumPL = gsub("P", "", NumPL)) %>%
      filter(NumAlt == NumPL,
             NumPL == NumADAlt) %>%
      select(CHROM, POS,REF,ALT,Dataset,AD.REF,AD.ALT,GQ,DP,PL.REF,PL.ALT) -> triplecdf
    
    rbind(mycdf, doublecdf, triplecdf) -> newcdf
    
    newcdf
  }

  if(yeast == TRUE){
    ChromKey <- data.frame(chromosomes = c("I", "II", "III", "IV", "V", "VI", "VII", "VIII",
                                         "IX", "X", "XI", "XII", "XIII", "XIV", "XV", "XVI", "M"),
                         CHROM = c("NC_001133.9", "NC_001134.8", "NC_001135.5", "NC_001136.10",
                                   "NC_001137.3", "NC_001138.5", "NC_001139.9", "NC_001140.6",
                                   "NC_001141.2", "NC_001142.9", "NC_001143.9", "NC_001144.5",
                                   "NC_001145.3", "NC_001146.8", "NC_001147.6", "NC_001148.4", "NC_001224.1"))

    resultscdf %>% left_join(.,ChromKey) %>% select(-CHROM) %>% mutate(CHROM = chromosomes) %>% select(-chromosomes) -> results
  }else{
    results <- resultscdf
  }
  return(results)

}
```

## Load in table and match to oak or wine parents

```{r}
setwd("C:/Users/Cassandra/Documents/GitHub/Sequencing/Analysis/")

parentSNPids <- cybrConvertParentalAlleles(ParentFiles = c("Wine_VCF.txt", "Oak_VCF.txt"), Truncate = TRUE)
parentSNPids %>% group_by(CHROM, POS) %>% summarize(Type = Type, Unique = length(unique(Type))) -> pSNPs

```

```{r, message = FALSE, warning=FALSE}
#testfile <- "C:/Users/cassa/Downloads/AllZivAIG.REF_NC_001143.9.SortedCat.vcf.output.table"


myfile <- "C:/Users/Cassandra/Documents/Data_NYU/Sequencing/ZIV_AIGs.SortedCat.vcf.output.table"

read.table(myfile, header = TRUE) -> testZiv_rawdata

unique(testZiv_rawdata$CHROM)

cybrInputGATKTable2(myfile) %>% mutate(Coverage = as.numeric(AD.REF) + as.numeric(AD.ALT)) %>%
  select(POS, CHROM, Dataset, GQ, AD.REF, AD.ALT, Coverage) -> Ziv_rawdata

```

## Actually determine which read is which

```{r}

#SMOOTHING ETC
Ziv_rawdata %>% #head(3000) %>%
  merge(parentSNPids) %>% mutate(REFW = as.numeric(Type == "Wine"), REFO = as.numeric(Type == "Oak")) %>%
  group_by(Dataset, CHROM, POS) %>%
  mutate(Wine = max(REFW * as.numeric(AD.REF), REFO * as.numeric(AD.ALT)),
         Oak = max(REFW * as.numeric(AD.ALT), REFO * as.numeric(AD.REF))) %>%
  select(Dataset, POS, CHROM, Coverage, Wine, Oak) %>%
  pivot_longer(c(Oak, Wine), names_to = "Allele", values_to = "Reads") -> Ziv_rawdata_called

# Ziv_rawdata_called %>% filter(CHROM == "II") %>%
#   ggplot(aes(x = POS, y = Dataset, color = Reads)) + geom_tile()

################################################################################
Ziv_rawdata_called %>% group_by(Dataset, CHROM, Allele) %>% arrange(POS) %>%
  reframe(POS = POS, SmoothCount = ceiling(frollapply(Reads, n = 300, FUN = median, align = "center", na.rm = TRUE))) -> Ziv_rawdata_smoothed #%>% na.omit()

# Ziv_rawdata_smoothed %>% filter(CHROM == "II") %>%
#   ggplot(aes(x = POS, y = Dataset, color = SmoothCount)) + geom_tile()
```


```{r, eval = FALSE}
#Checking to see how many of these are missing
Ziv_rawdata_smoothed %>% filter(CHROM == "II") %>%
  ggplot(aes(x = POS, y = Dataset, color = SmoothCount)) + geom_tile()

```

```{r, fig.width=12, fig.height=6}
Ziv_rawdata_smoothed %>% pivot_wider(names_from = Allele, values_from = SmoothCount) %>% unnest() %>%
  mutate(logOdds = log(Wine/Oak)) -> Ziv_logodds

Ziv_logodds %>% na.omit() %>%
  ggplot(aes(x = POS, y = logOdds, color = Dataset)) + 
    geom_line(alpha = 0.8, size = 0.5) +
    facet_grid(~CHROM, scales = "free", space = "free") +
  theme(legend.position = "bottom")

```



# Loading in my AIG data


```{r}
CB_AIGs <- readRDS("AIG_CFZ_rawdata.rds")

#SMOOTHING ETC
CB_AIGs %>% #head(3000) %>%
  merge(parentSNPids) %>% mutate(REFW = as.numeric(Type == "Wine"), REFO = as.numeric(Type == "Oak")) %>%
  group_by(Dataset, CHROM, POS) %>%
  mutate(Wine = max(REFW * as.numeric(AD.REF), REFO * as.numeric(AD.ALT)),
         Oak = max(REFW * as.numeric(AD.ALT), REFO * as.numeric(AD.REF))) %>%
  select(Dataset, POS, CHROM, Coverage, Wine, Oak) %>%
  pivot_longer(c(Oak, Wine), names_to = "Allele", values_to = "Reads") -> CB_AIGs_called

CB_AIGs_called %>% mutate(locus = paste(CHROM, POS)) %>% filter(locus %in% exclKEY$locus == FALSE) %>% select(-locus) -> CB_AIGs_called

CB_AIGs_called %>% group_by(Dataset, CHROM, Allele) %>% arrange(POS) %>%
  reframe(POS = POS, SmoothCount = ceiling(frollapply(Reads, n = 300, FUN = median, align = "center", na.rm = TRUE))) -> CB_AIGs_smoothed 

CB_AIGs_smoothed %>%
  pivot_wider(names_from = Allele, values_from = SmoothCount) %>% unnest() %>% mutate(logOdds = log(Wine/Oak)) %>%
  mutate(Dataset = gsub("H5LHYDRX5_n01_", "", Dataset)) %>%
  mutate(Dataset = gsub(".fastq", "", Dataset)) %>%
  separate(Dataset, into = c("Bulk", "Rep")) %>%
  filter(Bulk %in% c("C", "F", "Z", "U")) -> CB_AIGs_logOdds

CB_AIGs_called %>%
  pivot_wider(names_from = Allele, values_from = Reads) %>% unnest() %>% mutate(logOdds = log(Wine/Oak)) %>%
  mutate(Dataset = gsub("H5LHYDRX5_n01_", "", Dataset)) %>%
  mutate(Dataset = gsub(".fastq", "", Dataset)) %>%
  separate(Dataset, into = c("Bulk", "Rep")) %>%
  filter(Bulk %in% c("C", "F", "Z", "U")) -> CB_AIGs_logOdds_unsmoothed

```

```{r, fig.width=12, fig.height=6}
CB_AIGs_logOdds %>% na.omit() %>%
  ggplot(aes(x = POS, y = logOdds, color = Bulk)) + 
    geom_line(alpha = 0.4, size = 0.5) +
    facet_grid(~CHROM, scales = "free", space = "free") +
  theme(legend.position = "none")
```

```{r, fig.width=12, fig.height=6}
# CB_AIGs_logOdds %>% mutate(Dataset = paste("CB_AIG ", Bulk, Rep)) %>%
#   select(Dataset, CHROM, POS, Oak, Wine, logOdds) %>%
#   rbind(Ziv_logodds) -> comparison

CB_AIGs_logOdds_unsmoothed %>% filter(abs(logOdds) != Inf) %>%
  mutate(Dataset = paste("CB_AIG ", Bulk, Rep)) %>%
  select(Dataset, CHROM, POS, Oak, Wine, logOdds) %>%
  rbind(Ziv_logodds) -> comparison

comparison %>% filter(CHROM %in% c("I", "M") == FALSE) %>%
  ggplot(aes(x = POS, y = logOdds, color = Dataset)) + 
    geom_line(alpha = 0.4, size = 0.5) +
    facet_grid(~CHROM, scales = "free", space = "free") +
  scale_color_manual(values = c("orchid","orchid","orchid","orchid","orchid","orchid","orchid","orchid",
                                "black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")) +
  theme(legend.position = "none") +
  ggtitle("logOdds of Ziv AIGs (black) vs CB AIGs (purple)")


```


## Look for sporulation genes

IME1, RME1, and RSF1

```{r, fig.width=12, fig.height=6}
sgd_orfs <- read.csv("C:/Users/Cassandra/Documents/R_FileTransfer/SGD_ORFs.csv")

genes <- c("IME1", "RME1", "RSF1")
sgd_orfs %>% filter(Gene.symbol %in% genes) %>%
  mutate(CHROM = gsub("chr", "", Gene.chromosome.primaryIdentifier)) -> sgd_spo

comparison %>% filter(CHROM %in% c("I", "M") == FALSE) %>%
  ggplot(aes(x = POS, y = logOdds, color = Dataset)) + 
    geom_line(alpha = 0.4, size = 0.5) +
  geom_hline(yintercept = 0) +
  geom_vline(data = sgd_spo, aes(xintercept = Gene.chromosomeLocation.start, linetype = Gene.symbol), 
             size = 1, alpha = 0.8, color = "lightblue") +
    facet_grid(~CHROM, scales = "free", space = "free") +
  scale_color_manual(values = c("orchid","orchid","orchid","orchid","orchid","orchid","orchid","orchid",
                                "black","black","black","black","black","black","black","black","black","black","black","black","black","black","black")) +
  theme(legend.position = "bottom") +
  ggtitle("logOdds of Ziv AIGs (black) vs CB AIGs (purple)")


```




## What do the AIGs actually say?

```{r, fig.width=12, fig.height=6}
CB_AIGs_logOdds %>% filter(Bulk == "U") %>% group_by(CHROM, POS) %>% summarize(UMean = mean(logOdds)) -> Unselected_Avg

CB_AIGs_logOdds %>% merge(Unselected_Avg) %>% mutate(Diff = logOdds - UMean) -> logDiff

logDiff %>% filter(CHROM != "M") %>% ggplot(aes(x = POS, y = Diff, color = Bulk, linetype = Rep)) + 
    geom_line(alpha = 0.8, size = 0.5) +
  geom_hline(yintercept = 0) +
    facet_grid(~CHROM, scales = "free", space = "free")

logDiff %>% filter(CHROM == "VIII") %>% ggplot() + 
    geom_line(aes(x = POS, y = Diff, color = Bulk, linetype = Rep),alpha = 0.8, size = 0.5) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = c(120091,121683)) +
  geom_vline(xintercept = c(212535,212720,214533,214718)) +
    facet_grid(~CHROM, scales = "free", space = "free")

logDiff %>% filter(CHROM == "XII") %>% ggplot() + 
    geom_line(aes(x = POS, y = Diff, color = Bulk, linetype = Rep),alpha = 0.8, size = 0.5) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = c(568567,570627)) +
    facet_grid(~CHROM, scales = "free", space = "free")

CB_AIGs_logOdds %>% filter(CHROM == "VIII") %>% ggplot() + 
    geom_line(aes(x = POS, y = logOdds, color = Bulk, linetype = Rep),alpha = 0.8, size = 0.5) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = c(120091,121683)) +
  geom_vline(xintercept = c(212535,212720,214533,214718)) +
    facet_grid(~CHROM, scales = "free", space = "free")


```

```{r, fig.width=12, fig.height=6}
#CHROMOSOME VIII
CB_AIGs_logOdds_unsmoothed %>% group_by(Bulk, CHROM, POS) %>% summarize(avg = mean(logOdds)) %>% 
  filter(CHROM == "VIII", Bulk %in% c("U", "C"), POS < (562643 - 30000), POS > 30000) %>% 
  filter(abs(avg) != Inf) -> CHROM8_AIG_logOdds_unsmoothed

CB_AIGs_logOdds_unsmoothed %>% filter(CHROM == "VIII", Bulk %in% c("U", "C"), POS < (562643 - 30000), POS > 30000) %>% ggplot() + 
    geom_line(aes(x = POS, y = logOdds, color = Bulk, linetype = Rep),alpha = 0.8, size = 0.5) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = c(120091,121683), alpha = 0.3) +
  geom_vline(xintercept = c(212535,212720,214533,214718), alpha = 0.3) +
    facet_grid(~CHROM, scales = "free", space = "free")

CHROM8_AIG_logOdds_unsmoothed %>% 
  ggplot() + 
  geom_vline(xintercept = c(105586,105703), size = 2, color = "gray", alpha = 0.2) +
    geom_line(aes(x = POS, y = avg, color = Bulk),alpha = 0.8, size = 0.5) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = c(212535,212720,214533,214718), alpha = 0.3) +
    facet_grid(~CHROM, scales = "free", space = "free")

CHROM8_AIG_logOdds_unsmoothed %>% 
  ggplot() + 
  geom_vline(xintercept = c(105586,105703), size = 2, color = "gray", alpha = 0.2) + #CEN
    
  geom_point(aes(x = POS, y = avg, color = Bulk), size = 3, shape = 21) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = c(212535,212720,214533,214718), alpha = 0.3) + #CUP1
  xlim(105703+100000, 214718 + 105703 - 100000) + #zoom in
    facet_grid(~CHROM, scales = "free", space = "free")+
  theme(axis.text.x=element_text()) +
  scale_color_manual(values = c("darkturquoise", "black"))

CHROM8_AIG_logOdds_unsmoothed %>% 
  ggplot() + 
  geom_vline(xintercept = c(105586,105703), size = 2, color = "gray", alpha = 0.2) + #CEN
    
  geom_point(aes(x = POS, y = avg, color = Bulk), size = 3, shape = 21) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = c(212535,212720,214533,214718)) + #CUP1
  #geom_vline(xintercept = c(105703+80000, 214718 + 105703 - 80000), color = "red") + #zoom in
    facet_grid(~CHROM, scales = "free", space = "free") +
  scale_color_manual(values = c("darkturquoise", "black"))

CHROM8_AIG_logOdds_unsmoothed %>% filter(POS > (105703+80000), POS < 212535) %>% arrange(desc(avg))

```

```{r}
################################################################################
#Chromosome XII

CB_AIGs_logOdds_unsmoothed %>% filter(CHROM == "XII", Bulk %in% c("U", "C"), POS < (1078177 - 30000), POS > 30000) %>% ggplot() + 
    geom_line(aes(x = POS, y = logOdds, color = Bulk, linetype = Rep),alpha = 0.8, size = 0.5) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = c(568567,570627), alpha = 0.3) +
    facet_grid(~CHROM, scales = "free", space = "free")



CB_AIGs_logOdds_unsmoothed %>% group_by(Bulk, CHROM, POS) %>% summarize(avg = mean(logOdds)) %>% 
  filter(CHROM == "XII", Bulk %in% c("U", "C"), POS < (1078177 - 30000), POS > 30000) %>% 
  ggplot() + 
    geom_vline(xintercept = c(150828,150947), size = 2, color = "gray", alpha = 0.2) +
    geom_line(aes(x = POS, y = avg, color = Bulk),alpha = 0.8, size = 0.5) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = c(568567,570627), alpha = 0.3) +
    facet_grid(~CHROM, scales = "free", space = "free")

```


# Kernel testing

```{r}
CHROM8_AIG_logOdds_unsmoothed %>% filter(Bulk == "C") %>% arrange(POS) -> testkernel

testkernelmat <- matrix(c(testkernel$POS, testkernel$avg), ncol = 2)
testpost <- smooth_ksmooth(testkernelmat, smoothness = 0.1, bandwidth = 100)

plot(testkernelmat[,1], testpost[,1])

dim(testkernelmat)
dim(testpost)

# plot(smooth_ksmooth(testkernelmat, smoothness = 0.1, bandwidth = 100), main = "0.1")
# plot(smooth_ksmooth(testkernelmat, smoothness = 1, bandwidth = 100), main = "1")
# plot(smooth_ksmooth(testkernelmat, smoothness = 10, bandwidth = 100), main = "10")
# plot(smooth_ksmooth(testkernelmat, smoothness = 100, bandwidth = 100), main = "100")

plot(smooth_ksmooth(testkernelmat, bandwidth = 100), main = "100")
plot(smooth_ksmooth(testkernelmat, bandwidth = 200), main = "200")
plot(smooth_ksmooth(testkernelmat, bandwidth = 500), main = "500")
plot(smooth_ksmooth(testkernelmat, bandwidth = 1000), main = "1000")
plot(smooth_ksmooth(testkernelmat, bandwidth = 5000), main = "5000")

smoothed_5k <- smooth_ksmooth(testkernelmat, bandwidth = 5000)

data.frame(smoothed_5k) %>% select(POS = X1, avg = X2) %>% mutate(TEST = "smoothed") -> test5k
testkernel %>% select(POS, avg) %>% mutate(TEST = "raw data") %>%
  rbind(test5k) %>%
  ggplot(aes(x = POS, y = avg, color = TEST)) + geom_line()

test5k %>% arrange(avg) %>% head()

#212354 - is this cup1?

212535 - 212354
```


